baseURL: "https://joaonsantos.dev/"
title: joaonsantos blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: joaonsantos blog
  description: "Personal blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["/favicon.ico"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
            I tend to post things I find interesting here.

            - Hopefully you find that to be the case for you as well. 😉

  socialIcons:
    - name: github
      url: "https://github.com/joaonsantos"
    - name: linkedin
      url: "https://www.linkedin.com/in/joaopns"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/11149010/jo%c3%a3o-santos"
    - name: twitter
      url: "https://twitter.com/joaopns05"
    
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true
      
    googleanalytics:
        disabled: true
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    googleanalytics:
        disableInlineCSS: true
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true