baseURL: "https://blog.joaonsantos.dev/"
title: Implicitly Explicit
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Implicitly Explicit
  description: "João Santos' personal blog."
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["/favicon.ico"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      - Here you can find some ramblings and experiments that I come up with.

      - Opinions are my own.

  socialIcons:
    - name: github
      url: "https://github.com/joaonsantos"
    - name: linkedin
      url: "https://www.linkedin.com/in/joaopns"
    - name: mastodon
      url: "https://hachyderm.io/@ackrst"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/11149010/jo%c3%a3o-santos"
    
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true
      
    googleanalytics:
        disabled: true
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    googleanalytics:
        disableInlineCSS: true
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
