version: '3'

services:
  blog-nginx:
    image: blog-nginx
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - "443:80"
    volumes:
      - web-root:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    networks:
      - app
    depends_on:
      - blog-nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email joaopns05@gmail.com --agree-tos --no-eff-email -d joaonsantos.dev  -d www.joaonsantos.dev

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app:
