FROM node:alpine as builder

WORKDIR /app
COPY . ./
RUN npm install
RUN npm run build

FROM nginx:alpine

COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/public /usr/share/nginx/html
COPY --from=builder /app/dist /usr/share/nginx/html/dist

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
